name: Changesets

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'verdaccio/verdaccio'
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.verdaccio.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}

      - name: install pnpm
        run: npm i pnpm@latest -g
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: setup pnpm config registry
        run: pnpm config set registry https://registry.verdaccio.org

      - name: install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}

      - name: build
        run: pnpm build

      - name: create versions
        uses: verdaccio/changeset-action@master
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}
