name: Changesets

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master


jobs:
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@master
        with:
          node-version: 12
        env:
          NPM_TOKEN_: ${{ secrets.NPMJS_TOKEN }}
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: install dependencies
        run: pnpm install
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=test" > .npmrc        
      - name: cat npmrc
        run: cat .npmrc         
      - name: npm whoami
        run: npm whoami   
      - name: create versions
        uses: changesets/action@master
        with:
          version: yarn ci:version
          publish: yarn ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN_: ${{ secrets.NPMJS_TOKEN }}
