name: Changesets

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'juanpicado/changeset_test'
    steps:
      - name: checkout code repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@master
        with:
          node-version: 12
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        #   NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      # - name: Creating .npmrc
      #   run: |
      #     cat << EOF > "$HOME/.npmrc"
      #       //registry.npmjs.org/:_authToken=$NPMJS_TOKEN
      #     EOF
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: install dependencies
        run: pnpm install
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: create versions
        uses: changesets/action@master
        with:
          version: yarn ci:version
          publish: yarn ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
