name: Changesets

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository == 'juanpicado/changeset_test'
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=my@email.com
            //registry.npmjs.org/:_authToken=$NPMJS_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      - name: install pnpm
        run: npm i pnpm@latest -g
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: setup pnpm config registry
        run: pnpm config set registry https://registry.verdaccio.org

      - name: install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: create versions
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
