name: Node CI

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master
      - next
      - 'changeset-release/master'
      - 'changeset-release/next'

  pull_request:
    branches:
      - master
      - next

env:
  CI: true
  PNPM_VERSION: 5.3.0
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  # Build the project and run tests on built files.
  build_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
      fail-fast: false

    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install pnpm
        run: sudo npm install pnpm@latest

      - name: install dependencies
        run: pnpm install
